name: Deploy on Push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/ZX16-ISS-G3
            git pull origin main
            cd /z16-sim
            npm install
            npm run build
            pm2 restart z16
